// This file is automatically generated by qtc from "basepage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line contributors/basepage.qtpl:3
package contributors

//line contributors/basepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line contributors/basepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line contributors/basepage.qtpl:4
type Page interface {
	//line contributors/basepage.qtpl:4
	Title() string
	//line contributors/basepage.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
	//line contributors/basepage.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
	//line contributors/basepage.qtpl:4
	Body() string
	//line contributors/basepage.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
	//line contributors/basepage.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line contributors/basepage.qtpl:4
}

// Page prints a page implementing Page interface.

//line contributors/basepage.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line contributors/basepage.qtpl:12
	qw422016.N().S(`
<html>
    <link type="text/css" rel="stylesheet" href="/static/css/default.css">
	<head>
		<title>`)
	//line contributors/basepage.qtpl:16
	p.StreamTitle(qw422016)
	//line contributors/basepage.qtpl:16
	qw422016.N().S(`</title>
	</head>
	<body>
		<h1>Админка контрибьюторов</h1>
		`)
	//line contributors/basepage.qtpl:20
	p.StreamBody(qw422016)
	//line contributors/basepage.qtpl:20
	qw422016.N().S(`
	</body>
</html>
`)
//line contributors/basepage.qtpl:23
}

//line contributors/basepage.qtpl:23
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line contributors/basepage.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line contributors/basepage.qtpl:23
	StreamPageTemplate(qw422016, p)
	//line contributors/basepage.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line contributors/basepage.qtpl:23
}

//line contributors/basepage.qtpl:23
func PageTemplate(p Page) string {
	//line contributors/basepage.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
	//line contributors/basepage.qtpl:23
	WritePageTemplate(qb422016, p)
	//line contributors/basepage.qtpl:23
	qs422016 := string(qb422016.B)
	//line contributors/basepage.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
	//line contributors/basepage.qtpl:23
	return qs422016
//line contributors/basepage.qtpl:23
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line contributors/basepage.qtpl:28
type BasePage struct{}

//line contributors/basepage.qtpl:29
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line contributors/basepage.qtpl:29
qw422016.N().S(`This is a base title`) }

//line contributors/basepage.qtpl:29
//line contributors/basepage.qtpl:29
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line contributors/basepage.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line contributors/basepage.qtpl:29
	p.StreamTitle(qw422016)
	//line contributors/basepage.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line contributors/basepage.qtpl:29
}

//line contributors/basepage.qtpl:29
func (p *BasePage) Title() string {
	//line contributors/basepage.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line contributors/basepage.qtpl:29
	p.WriteTitle(qb422016)
	//line contributors/basepage.qtpl:29
	qs422016 := string(qb422016.B)
	//line contributors/basepage.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line contributors/basepage.qtpl:29
	return qs422016
//line contributors/basepage.qtpl:29
}

//line contributors/basepage.qtpl:30
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line contributors/basepage.qtpl:30
qw422016.N().S(`This is a base body`) }

//line contributors/basepage.qtpl:30
//line contributors/basepage.qtpl:30
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	//line contributors/basepage.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line contributors/basepage.qtpl:30
	p.StreamBody(qw422016)
	//line contributors/basepage.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line contributors/basepage.qtpl:30
}

//line contributors/basepage.qtpl:30
func (p *BasePage) Body() string {
	//line contributors/basepage.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
	//line contributors/basepage.qtpl:30
	p.WriteBody(qb422016)
	//line contributors/basepage.qtpl:30
	qs422016 := string(qb422016.B)
	//line contributors/basepage.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
	//line contributors/basepage.qtpl:30
	return qs422016
//line contributors/basepage.qtpl:30
}
