// This file is automatically generated by qtc from "newRequestsList.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Requests list page template. Implements BasePage methods.
//

//line contributors/newRequestsList.qtpl:3
package contributors

//line contributors/newRequestsList.qtpl:3
import (
	timeformat "github.com/bfg-dev/crypto-core/pkg/helpers/timeformat"
	contributor "github.com/bfg-dev/crypto-core/pkg/services/contributor"
)

//line contributors/newRequestsList.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line contributors/newRequestsList.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line contributors/newRequestsList.qtpl:10
type NewRequestsListPage struct {
	Requests []contributor.UserMissionRequest
}

//line contributors/newRequestsList.qtpl:15
func (p *NewRequestsListPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line contributors/newRequestsList.qtpl:15
	qw422016.N().S(`
	This is table page
`)
//line contributors/newRequestsList.qtpl:17
}

//line contributors/newRequestsList.qtpl:17
func (p *NewRequestsListPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line contributors/newRequestsList.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line contributors/newRequestsList.qtpl:17
	p.StreamTitle(qw422016)
	//line contributors/newRequestsList.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line contributors/newRequestsList.qtpl:17
}

//line contributors/newRequestsList.qtpl:17
func (p *NewRequestsListPage) Title() string {
	//line contributors/newRequestsList.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line contributors/newRequestsList.qtpl:17
	p.WriteTitle(qb422016)
	//line contributors/newRequestsList.qtpl:17
	qs422016 := string(qb422016.B)
	//line contributors/newRequestsList.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line contributors/newRequestsList.qtpl:17
	return qs422016
//line contributors/newRequestsList.qtpl:17
}

//line contributors/newRequestsList.qtpl:19
func (p *NewRequestsListPage) StreamBody(qw422016 *qt422016.Writer) {
	//line contributors/newRequestsList.qtpl:19
	qw422016.N().S(`

    <h2>Список новых запросов на миссии</h2>

	<table>
	    <thead>
	        <tr>
	            <th>Дата</th>
	            <th>Пользователь</th>
	            <th>Миссия</th>
	            <th>Параметры запроса</th>
	            <th>&nbsp;</th>
	        </tr>
	    </thead>
	    <tbody>
	`)
	//line contributors/newRequestsList.qtpl:34
	for _, request := range p.Requests {
		//line contributors/newRequestsList.qtpl:34
		qw422016.N().S(`
	    <form method="post" action="/admin/SetUserRequestStatus">
	    <input type="hidden" name="id" value="`)
		//line contributors/newRequestsList.qtpl:36
		qw422016.N().D(int(request.ID))
		//line contributors/newRequestsList.qtpl:36
		qw422016.N().S(`">
	    <tr>
	        <td>`)
		//line contributors/newRequestsList.qtpl:38
		qw422016.E().S(request.CreatedAt.Format(timeformat.Date))
		//line contributors/newRequestsList.qtpl:38
		qw422016.N().S(`</td>
            <td>`)
		//line contributors/newRequestsList.qtpl:39
		qw422016.E().S(request.UserName)
		//line contributors/newRequestsList.qtpl:39
		qw422016.N().S(`</td>
            <td>`)
		//line contributors/newRequestsList.qtpl:40
		qw422016.E().S(request.Mission)
		//line contributors/newRequestsList.qtpl:40
		qw422016.N().S(`</td>
            <td>
            `)
		//line contributors/newRequestsList.qtpl:42
		for key, param := range request.MissionParameters {
			//line contributors/newRequestsList.qtpl:42
			qw422016.N().S(`
                `)
			//line contributors/newRequestsList.qtpl:43
			qw422016.E().S(key)
			//line contributors/newRequestsList.qtpl:43
			qw422016.N().S(`: <a href="`)
			//line contributors/newRequestsList.qtpl:43
			qw422016.E().S(param)
			//line contributors/newRequestsList.qtpl:43
			qw422016.N().S(`" target="_blank">link</a>
                <br>
            `)
			//line contributors/newRequestsList.qtpl:45
		}
		//line contributors/newRequestsList.qtpl:45
		qw422016.N().S(`
            </td>
            <td><button type="submit" name="status" value="approved">Одобрить</button>
                <button type="submit" name="status" value="rejected">Отклонить</button>
            </td>
	    </tr>
	    </form>
	`)
		//line contributors/newRequestsList.qtpl:52
	}
	//line contributors/newRequestsList.qtpl:52
	qw422016.N().S(`
	    </tbody>
	</table>
`)
//line contributors/newRequestsList.qtpl:55
}

//line contributors/newRequestsList.qtpl:55
func (p *NewRequestsListPage) WriteBody(qq422016 qtio422016.Writer) {
	//line contributors/newRequestsList.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line contributors/newRequestsList.qtpl:55
	p.StreamBody(qw422016)
	//line contributors/newRequestsList.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line contributors/newRequestsList.qtpl:55
}

//line contributors/newRequestsList.qtpl:55
func (p *NewRequestsListPage) Body() string {
	//line contributors/newRequestsList.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
	//line contributors/newRequestsList.qtpl:55
	p.WriteBody(qb422016)
	//line contributors/newRequestsList.qtpl:55
	qs422016 := string(qb422016.B)
	//line contributors/newRequestsList.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
	//line contributors/newRequestsList.qtpl:55
	return qs422016
//line contributors/newRequestsList.qtpl:55
}
